FROM node:22-alpine
RUN apk add --no-cache python3 make g++ curl jq && npm install -g openclaw

COPY entrypoint-openclaw.sh /entrypoint-openclaw.sh
RUN chmod +x /entrypoint-openclaw.sh

COPY configs /configs

CMD ["sh", "/entrypoint-openclaw.sh"]