FROM node:22-alpine
RUN apk add --no-cache python3 make g++ curl jq && npm install -g openclaw

COPY entrypoint-combined.sh /entrypoint-combined.sh
RUN chmod +x /entrypoint-combined.sh

COPY configs /configs

CMD ["sh", "/entrypoint-combined.sh"]